server:
  port: 8080

spring:
  application:
    name: urm-notify-service
  data:
    mongodb:
      uri: mongodb://urm-ops:Tp_0INPtFtzvuT6t@10.129.5.82:8635,10.129.5.15:8635,10.129.5.62:8635/urm?authSource=urm&authMechanism=SCRAM-SHA-1&replicaSet=replica
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://101.35.221.49:5432/notify
    username: postgres
    password: '0224'
  kafka:
    bootstrap-servers: 101.35.221.49:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 101.35.221.49:9092
    consumer:
      bootstrap-servers: 101.35.221.49:9092
      group-id: urm-notify-service
      #auto-offset-reset: earliest
      auto-offset-reset: latest
      enable-auto-commit: false
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 10
      poll-timeout: 5000
      ack-mode: manual_immediate
    urm_topics:
      sms_topic: urm_sms_notify_topic
      notify_topic: urm_sms_notify_topic,urm_one_notify_topic
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
notify:
  sms:
    host: https://rtcsms.cn-north-1.myhuaweicloud.com:10743
    url:
      batchSendSms: /sms/batchSendSms/v1
      batchSendDiffSms: /sms/batchSendDiffSms/v1
  app:
    host: http://119.3.90.36:31469
    ak: 7f92ba784eee11eaa84e10e7c63338a5
    sk: 85a37e984eee11eaa84e10e7c63338a5
    url:
      pushPath: /oneapp-content-service/v2/api/message/serviceMessagePushV2
  white-list:
    open: true
    mobiles: 17621039114
    emails: 1035071992@qq.com
